# Generated by Django 2.2 on 2020-05-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='赛事名称')),
                ('addr', models.CharField(max_length=128, verbose_name='比赛地点')),
                ('date', models.CharField(max_length=128, verbose_name='比赛时间')),
                ('person', models.CharField(max_length=128, verbose_name='比赛队伍')),
                ('score', models.IntegerField(max_length=128, verbose_name='赛事得分')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='新闻标题')),
                ('info', models.TextField(verbose_name='新闻内容')),
            ],
        ),
        migrations.CreateModel(
            name='Tieba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='新闻标题')),
                ('info', models.TextField(verbose_name='新闻内容')),
            ],
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='usertype',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=128, verbose_name='结果')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Match', verbose_name='关联赛事名称')),
            ],
        ),
    ]
