# Generated by Django 2.2 on 2020-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200512_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='person',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='person',
            field=models.CharField(default='default', max_length=128, verbose_name='比赛队伍'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=100, max_length=128, verbose_name='赛事得分'),
            preserve_default=False,
        ),
    ]
