# Generated by Django 2.2 on 2020-05-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200514_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieba',
            name='info',
            field=models.TextField(verbose_name='帖子内容'),
        ),
        migrations.AlterField(
            model_name='tieba',
            name='title',
            field=models.CharField(max_length=128, verbose_name='帖子标题'),
        ),
    ]
